### ISSUE TITLE
Improvement: translating all the respective file names into English

### ISSUE THREAD

**Issue by madiko** [openbikesensor/openbikesensor.github.io#57] opened 2021-03-23 22:24 UTC
Task at hand: 

switching developer communication to English (work in progress)

1. Checking all file names and establishing a file name convention (work in progress).
2. Then renaming everything.

Example: 
https://github.com/openbikesensor/openbikesensor.github.io/tree/main/content/docs/hardware/v00.03/build-instructions/images

**Comment by opatut** [comment] 2021-09-12 07:00
This seems to be a duplicate of #6.

**Closed by opatut** 2021-09-12 07:00 UTC
Labels: technical
